backend:
  name: github
  repo: puserve/puserve.github.io
  branch: main
  auth_type: pkce
  app_id: "Ov23li1puh2q6WY4DSnY"

media_folder: "uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

collections:
  - name: "events"
    label: "Events"
    folder: "_events"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Judul Event", name: "title", widget: "string"}
      - {label: "Status Event", name: "status", widget: "select", options: ["Upcoming", "Running", "Past"]}
      - {label: "Tanggal Event", name: "date", widget: "datetime"}
      - {label: "Jumlah Peserta", name: "attendees", widget: "string", required: false}
      - {label: "Target/Hasil Progress", name: "result_text", widget: "string"}
      - {label: "Poster", name: "thumbnail", widget: "image"}
      - {label: "Deskripsi", name: "body", widget: "markdown"}
